const fs = require('fs');
const content = `
Cardio	Cardio	—	Treadmill Run	Steady State	Machine	Gym	Beginner	Cardio		https://www.pexels.com/search/videos/treadmill/		https://www.youtube.com/results?search_query=treadmill+form	Keep posture upright	Esteira (Corrida)	Cinta de correr	Ritmo Constante	Ritmo Constante	Esteira — Ritmo Constante	Cinta de correr — Ritmo Constante	cardio_cardio_treadmill_run_steady_state_machine_gym_beginner
Cardio	Cardio	—	Elliptical	Steady State	Machine	Gym	Beginner	Cardio		https://www.pexels.com/search/videos/elliptical/		https://www.youtube.com/results?search_query=elliptical+machine+form	Use handles	Elíptico	Elíptica	Padrão	Estándar	Elíptico — Padrão	Elíptica — Estándar	cardio_cardio_elliptical_steady_state_machine_gym_beginner
Cardio	Cardio	Back	Rowing Machine	Intervals	Machine	Gym	Intermediate	Cardio		https://www.pexels.com/search/videos/rowing+machine/		https://www.youtube.com/results?search_query=rowing+machine+form	Drive with legs	Remo (Máquina)	Remo (Máquina)	Intervalado	Intervalos	Remo (Máquina) — Intervalado	Remo (Máquina) — Intervalos	cardio_cardio_rowing_machine_intervals_machine_gym_intermediate
Cardio	Cardio	Legs	Stair Climber	Steady State	Machine	Gym	Intermediate	Cardio		https://www.pexels.com/search/videos/stair+climber/		https://www.youtube.com/results?search_query=stair+master+form	Don't lean on handles	Simulador de Escada	Escaladora	Padrão	Estándar	Simulador de Escada — Padrão	Escaladora — Estándar	cardio_cardio_stair_climber_steady_state_machine_gym_intermediate
Cardio	Cardio	—	Stationary Bike	Spinning	Machine	Gym	Beginner	Cardio		https://www.pexels.com/search/videos/stationary+bike/		https://www.youtube.com/results?search_query=spinning+bike+setup	Adjust seat height	Bicicleta Ergométrica	Bicicleta Estática	Spinning	Spinning	Bicicleta Ergométrica — Spinning	Bicicleta Estática — Spinning	cardio_cardio_stationary_bike_spinning_machine_gym_beginner
Cardio	Cardio	—	Jumping Jacks	Bodyweight	Bodyweight	Home	Beginner	Cardio		https://www.pexels.com/search/videos/jumping+jacks/		https://www.youtube.com/results?search_query=jumping+jacks+form	Land softly	Polichinelos	Jumping Jacks	Peso do corpo	Peso corporal	Polichinelos — Peso do corpo	Jumping Jacks — Peso corporal	cardio_cardio_jumping_jacks_bodyweight_bodyweight_home_beginner
Cardio	Cardio	Full Body	Burpees	Standard	Bodyweight	Home	Advanced	Cardio		https://www.pexels.com/search/videos/burpees/		https://www.youtube.com/results?search_query=burpee+form	Full extension at top	Burpees	Burpees	Padrão	Estándar	Burpees — Padrão	Burpees — Estándar	cardio_cardio_burpees_standard_bodyweight_home_advanced
Cardio	Cardio	Legs	High Knees	Bodyweight	Bodyweight	Home	Beginner	Cardio		https://www.pexels.com/search/videos/high+knees/		https://www.youtube.com/results?search_query=high+knees+exercise	Knees to hip level	Corrida Estacionária (High Knees)	Rodillas Arriba	Peso do corpo	Peso corporal	Corrida Estacionária (High Knees) — Peso do corpo	Rodillas Arriba — Peso corporal	cardio_cardio_high_knees_bodyweight_bodyweight_home_beginner
Cardio	Cardio	—	Jump Rope	Basic Bounce	Rope	Home	Intermediate	Cardio		https://www.pexels.com/search/videos/jump+rope/		https://www.youtube.com/results?search_query=jump+rope+basics	Stay on toes	Pular Corda	Saltar la cuerda	Básico	Básico	Pular Corda — Básico	Saltar la cuerda — Básico	cardio_cardio_jump_rope_basic_bounce_rope_home_intermediate
Cardio	Cardio	—	Shadow Boxing	Freestyle	Bodyweight	Home	Beginner	Cardio		https://www.pexels.com/search/videos/shadow+boxing/		https://www.youtube.com/results?search_query=shadow+boxing+workout	Keep guard up	Sombra de Boxe	Sombra de Boxeo	Livre	Libre	Sombra de Boxe — Livre	Sombra de Boxeo — Libre	cardio_cardio_shadow_boxing_freestyle_bodyweight_home_beginner
`;
fs.appendFileSync('IMPORT_EXERCICIOS.txt', content);
console.log('Appended cardio exercises.');
